# Generated by Django 5.2.7 on 2026-01-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_trees_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trees',
            name='owner_name',
        ),
    ]
