# Generated by Codex on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_remove_trees_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trees',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo_trees/'),
        ),
        migrations.AlterField(
            model_name='treesimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo_trees/'),
        ),
    ]
