# Generated by Django 5.2.7 on 2026-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_alter_trees_image_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trees',
            options={'verbose_name': 'дерево', 'verbose_name_plural': 'деревья'},
        ),
        migrations.AlterModelOptions(
            name='treesimages',
            options={'verbose_name': 'фото дерева', 'verbose_name_plural': 'фото деревьев'},
        ),
        migrations.AlterField(
            model_name='trees',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='dedicated_to',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Посвящено'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photo_trees/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='trees',
            name='title',
            field=models.CharField(default='Дерево', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='treesimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photo_trees/', verbose_name='Фото'),
        ),
    ]
