# Generated by Django 5.2.7 on 2026-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'промокод', 'verbose_name_plural': 'промокоды'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
    ]
