# Generated by Codex on 2026-01-24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='owner_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Owner first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='owner_last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Owner last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='owner_surname',
            field=models.CharField(default='', max_length=100, verbose_name='Owner surname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='owner_birthday',
            field=models.DateField(
                default=datetime.date(1970, 1, 1),
                verbose_name='Birthday',
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='simpleuserprofile',
            old_name='is_employee',
            new_name='is_editor',
        ),
    ]
