# Generated by Django 5.2.7 on 2026-01-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_partner_owner_fields_and_rename_is_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='owner_first_name',
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_birthday',
            field=models.DateField(verbose_name='owner_birthday'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner surname'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Is editor'),
        ),
    ]
