# Generated by Codex on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_remove_partnerprofile_owner_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='owner_first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Owner first name'),
            preserve_default=False,
        ),
    ]
