# Generated by Django 5.2.7 on 2026-01-30 13:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paymentwebhookevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'verbose_name': 'профиль партнера', 'verbose_name_plural': 'профили партнеров'},
        ),
        migrations.AlterModelOptions(
            name='paymentwebhookevent',
            options={'verbose_name': 'payment webhook event', 'verbose_name_plural': 'payment webhook events'},
        ),
        migrations.AlterModelOptions(
            name='simpleuserprofile',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_birthday',
            field=models.DateField(verbose_name='Дата рождения владельца'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_first_name',
            field=models.CharField(max_length=100, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия владельца'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='owner_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество владельца'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='is_editor',
            field=models.BooleanField(default=False, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='simpleuserprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
