# Generated by Django 5.2.7 on 2026-02-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_password_change_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordchangerequest',
            options={'verbose_name': 'запрос смены пароля', 'verbose_name_plural': 'запросы смены пароля'},
        ),
    ]
