# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_passwordchangerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='accountant_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email бухгалтера'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='accountant_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО бухгалтера'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='accountant_phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон бухгалтера'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email координатора'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='coordinator_fio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО координатора'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон координатора'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='inn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='ИНН'),
        ),
    ]
