# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Дизлайки'),
        ),
    ]
